name: "✨ Feature / Enhancement"
description: "Suggest a new feature or improvement."
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: input
    id: issue_number_title
    attributes:
      label: "Issue Number and Title"
      placeholder: "placeholder"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: "placeholder"
    validations:
      required: true
  - type: textarea
    id: previous_feature
    attributes:
      label: "Previous Feature (if applicable)"
      placeholder: "placeholder"
    validations:
      required: true
  - type: textarea
    id: proposed_feature
    attributes:
      label: "Proposed Feature"
      placeholder: "placeholder"
    validations:
      required: true
  - type: textarea
    id: step_to_reproduce
    attributes:
      label: "Steps to Reproduce or Use the Feature"
      placeholder: "placeholder"
    validations:
      required: true
  - type: input
    id: issue_link
    attributes:
      label: "Issue Link"
      placeholder: "placeholder"
    validations:
      required: true
